"""
Modul wrapper untuk menjalankan xTB (GFN2-xTB).
Referensi: old_model/Input_for_DFT,_xTB_Conformational_Energy,_and_Geometry_Distortion_Bound_within_the_SBU.ipynb

CATATAN: File ini membutuhkan xTB binary terinstall di PATH sistem.
Install: https://github.com/grimme-lab/xtb/releases
"""

import subprocess
import tempfile
import re
import os
from pathlib import Path

# Cek apakah xTB tersedia
XTB_AVAILABLE = False
try:
    result = subprocess.run(["xtb", "--version"], capture_output=True, text=True, timeout=10)
    XTB_AVAILABLE = result.returncode == 0
except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
    XTB_AVAILABLE = False


def atoms_positions_to_xyz(atoms: list, positions: list) -> str:
    """
    Konversi list atom dan posisi ke format XYZ string.

    Args:
        atoms: List simbol atom ['C', 'H', 'O', ...]
        positions: List posisi [[x, y, z], ...]

    Returns:
        str: Konten file XYZ
    """
    n = len(atoms)
    lines = [str(n), "Generated by MOF Analysis"]
    for symbol, pos in zip(atoms, positions):
        lines.append(f"{symbol}  {pos[0]:.6f}  {pos[1]:.6f}  {pos[2]:.6f}")
    return "\n".join(lines) + "\n"


def run_xtb_single_point(xyz_content: str) -> dict:
    """
    Jalankan xTB single point energy calculation.

    Command: xtb input.xyz --gfn2

    Args:
        xyz_content: Konten file XYZ (teks)

    Returns:
        dict: {energy_hartree, energy_kj_mol, success}
    """
    if not XTB_AVAILABLE:
        return {"energy_hartree": 0.0, "energy_kj_mol": 0.0,
                "success": False, "error": "xTB not installed"}

    with tempfile.TemporaryDirectory() as tmpdir:
        xyz_path = os.path.join(tmpdir, "input.xyz")
        with open(xyz_path, "w") as f:
            f.write(xyz_content)

        try:
            result = subprocess.run(
                ["xtb", "input.xyz", "--gfn2"],
                capture_output=True, text=True,
                cwd=tmpdir, timeout=300
            )

            # Parse energi dari output xTB
            energy = parse_xtb_energy(result.stdout)

            return {
                "energy_hartree": energy,
                "energy_kj_mol": round(energy * 2625.5, 4),  # Hartree → kJ/mol
                "success": True
            }
        except subprocess.TimeoutExpired:
            return {"energy_hartree": 0.0, "energy_kj_mol": 0.0,
                    "success": False, "error": "xTB timeout (>300s)"}
        except Exception as e:
            return {"energy_hartree": 0.0, "energy_kj_mol": 0.0,
                    "success": False, "error": str(e)}


def run_xtb_optimization(xyz_content: str) -> dict:
    """
    Jalankan xTB geometry optimization.

    Command: xtb input.xyz --opt --gfn2

    Returns:
        dict: {energy_hartree, energy_kj_mol, optimized_xyz, optimized_positions, success}
    """
    if not XTB_AVAILABLE:
        return {"energy_hartree": 0.0, "energy_kj_mol": 0.0,
                "optimized_xyz": "", "optimized_positions": [],
                "success": False, "error": "xTB not installed"}

    with tempfile.TemporaryDirectory() as tmpdir:
        xyz_path = os.path.join(tmpdir, "input.xyz")
        with open(xyz_path, "w") as f:
            f.write(xyz_content)

        try:
            result = subprocess.run(
                ["xtb", "input.xyz", "--opt", "--gfn2"],
                capture_output=True, text=True,
                cwd=tmpdir, timeout=600
            )

            energy = parse_xtb_energy(result.stdout)

            # Baca geometri yang sudah dioptimasi
            opt_xyz_path = os.path.join(tmpdir, "xtbopt.xyz")
            opt_xyz = ""
            opt_positions = []
            if os.path.exists(opt_xyz_path):
                with open(opt_xyz_path, "r") as f:
                    opt_xyz = f.read()
                opt_positions = parse_xyz_positions(opt_xyz)

            return {
                "energy_hartree": energy,
                "energy_kj_mol": round(energy * 2625.5, 4),
                "optimized_xyz": opt_xyz,
                "optimized_positions": opt_positions,
                "success": True
            }
        except subprocess.TimeoutExpired:
            return {"energy_hartree": 0.0, "energy_kj_mol": 0.0,
                    "optimized_xyz": "", "optimized_positions": [],
                    "success": False, "error": "xTB optimization timeout (>600s)"}
        except Exception as e:
            return {"energy_hartree": 0.0, "energy_kj_mol": 0.0,
                    "optimized_xyz": "", "optimized_positions": [],
                    "success": False, "error": str(e)}


def parse_xtb_energy(output: str) -> float:
    """
    Parse total energy dari output xTB.
    Cari baris: "TOTAL ENERGY" → extract nilai dalam Hartree.
    """
    for line in output.splitlines():
        if "TOTAL ENERGY" in line:
            match = re.search(r"(-?\d+\.\d+)", line)
            if match:
                return float(match.group(1))
    return 0.0


def parse_xyz_positions(xyz_content: str) -> list:
    """
    Parse posisi atom dari konten file XYZ.

    Returns:
        list: [[x, y, z], ...]
    """
    lines = xyz_content.strip().splitlines()
    if len(lines) < 3:
        return []

    positions = []
    for line in lines[2:]:  # Skip header (n_atoms + comment)
        parts = line.split()
        if len(parts) >= 4:
            try:
                positions.append([float(parts[1]), float(parts[2]), float(parts[3])])
            except ValueError:
                continue
    return positions


def calculate_delta_e(e_embedded_kj: float, e_free_kj: float) -> float:
    """
    Hitung ΔE = E_embedded - E_free.

    Nilai positif → linker tertekan/terdistorsi dalam MOF
    Nilai negatif → linker terstabilkan dalam MOF
    """
    return round(e_embedded_kj - e_free_kj, 4)
